### ISSUE TITLE
segmentation fault if local directory does not exist

### ISSUE THREAD

**Issue by edwins** [cyverse/irods_client_fuse#1]
Howdy,

I receive a segmentation fault if the local directory doesn't exist.

> irodsFs -oallow_other -oconnreuse -ometadatacachetimeout 3600 -opreloadblocks 5 somerandomdirectory
Segmentation fault (core dumped)

Thanks!

**Comment by iychoi** [comment]
Figuring this out.

**Comment by iychoi** [comment]
Fixed at commit cc509de
